apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: mani
  labels:           #changes commited in code will not be reflected in application.
    app: mani
spec:
  containers:
  - name: mypod1
    image: nginx:latest
    volumeMounts:
      - name: testvol
        mountPath: /usr/share/nginx/html
  volumes:
     - name: testvol
       gitRepo:
         repository: https://github.com/imr99/ecomm.git
         revision: master
         directory: .