apiVersion: v1
kind: Pod
metadata:
  name: mani
  namespace: mani
  labels:
     name: ebs-volume
spec:
  containers:
  - image: imr99/ecomm
    name: test-container
    volumeMounts:
    - mountPath: /usr/share/nginx/html/
      name: html
  volumes:
  - name: html
    # This AWS EBS volume must already exist.
    awsElasticBlockStore:
      volumeID: vol-0d5ce9c86b648b7bb
      fsType: ext4
