apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim1
  #namespace: mani
spec:
  storageClassName: high
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi